version: "3.9"

services:
  api-server:
    build:
      args:
        BACKEND_CONTEXT_PATH: $BACKEND_CONTEXT_PATH
        DOCKER_IMAGE_CONTEXT_PATH: $DOCKER_IMAGE_CONTEXT_PATH
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: $APP_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/api-server/Dockerfile
    container_name: paladin_api-server
    depends_on:
      - mongo
    environment:
      ADMIN_EMAIL: "admin@paladin.local"
      CLIENT_URL: "http://paladin.local"
      DEBUG_LOG: /var/log/app.log
      DEFAULT_LOCALE: "en_US"
      ENVIRONMENT: "development"
      ERROR_REPORTING: "true"
      FORCE_HTTPS: "false"
      INFO_EMAIL: "info@paladin.local"
      JWT_KEY: /run/secrets/paladin_jwt_key
      MAILER_HOST: "smtp.mailgun.org"
      MAILER_PORT: "587"
      MAILER_USER: postmaster@sandboxdc85f60c099b4ef28d752259b3a73dad.mailgun.org
      MAILER_PASSWORD: /run/secrets/paladin_mailer_password
      MONGO_INITDB_DATABASE: "paladin"
      MONGO_PASSWORD_FILE: /run/secrets/paladin_mongo_password
      MONGO_PORT: "27017"
      MONGO_HOST: "mongo"
      MONGO_USER: "paladin"
      REDIS_PORT: "6379"
      SITE_NAME: "Paladin"
    networks:
      - external
      - internal
    secrets:
      - paladin_jwt_key
      - paladin_mailer_password
      - paladin_mongo_password
    volumes:
      - $BACKEND_DIRECTORY:/home/dockeruser/backend
      - $DOCKER_DIRECTORY/images/api-server/php.ini:/usr/local/etc/php/php.ini
      - $API_SERVER_LOG_DIRECTORY:/var/log

  http-proxy:
    build:
      args:
        DOCKER_IMAGE_CONTEXT_PATH: $DOCKER_IMAGE_CONTEXT_PATH
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: $APP_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/http-proxy/Dockerfile
    container_name: paladin_http-proxy
    depends_on:
      - app-server
      - mongo-express
      - redis-admin
    networks:
      - external
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - $DOCKER_DIRECTORY/images/http-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - $HTTP_PROXY_LOG_DIRECTORY:/var/log/nginx

  mongo:
    build:
      args:
        DOCKER_IMAGE_CONTEXT_PATH: $DOCKER_IMAGE_CONTEXT_PATH
      context: $APP_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/mongo/Dockerfile
    container_name: paladin_mongo
    networks:
      - internal
    environment:
      MONGO_INITDB_DATABASE: "paladin"
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/paladin_mongo_root_password
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_PASSWORD_FILE: /run/secrets/paladin_mongo_password
      MONGO_USER: "paladin"
    secrets:
      - paladin_mongo_password
      - paladin_mongo_root_password
    volumes:
      - mongo:/data/db

  mongo-express:
    build:
      args:
        DOCKER_IMAGE_CONTEXT_PATH: $DOCKER_IMAGE_CONTEXT_PATH
      context: $APP_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/mongo-express/Dockerfile
    container_name: paladin_mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/paladin_mongo_root_password
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - external
      - internal
    restart: unless-stopped
    secrets:
      - paladin_mongo_password
      - paladin_mongo_root_password

  redis:
    build:
      context: $APP_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/redis/Dockerfile
    container_name: paladin_redis
    networks:
      - internal

  redis-admin:
    build:
      context: $APP_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/redis-admin/Dockerfile
    container_name: paladin_redis-admin
    depends_on:
      - redis
    environment:
      REDIS_1_HOST: "redis"
    networks:
      - external
      - internal

networks:
  internal:
  external:

secrets:
  paladin_jwt_key:
    file: $DOCKER_SECRET_DIRECTORY/paladin_jwt_key.txt
  paladin_mailer_password:
    file: $DOCKER_SECRET_DIRECTORY/paladin_mailer_password.txt
  paladin_mongo_password:
    file: $DOCKER_SECRET_DIRECTORY/paladin_mongo_password.txt
  paladin_mongo_root_password:
    file: $DOCKER_SECRET_DIRECTORY/paladin_mongo_root_password.txt

volumes:
  mongo: